## Submitted by: 

*   Venkat Mohit Sornapudi (2721697)
*   Clifton Roozendal (2534824)



In [1]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.4f}".format(x)})

In [2]:
P = np.zeros((91,91))
for i in range(P.shape[0]):
    for j in range(P.shape[1]):
        if j == 0:
            P[i,j] = 0.1 + 0.01*i
        if j == i+1:
            P[i,j] = 1 - P[i,0]
            
P

array([[0.1000, 0.9000, 0.0000, ..., 0.0000, 0.0000, 0.0000],
       [0.1100, 0.0000, 0.8900, ..., 0.0000, 0.0000, 0.0000],
       [0.1200, 0.0000, 0.0000, ..., 0.0000, 0.0000, 0.0000],
       ...,
       [0.9800, 0.0000, 0.0000, ..., 0.0000, 0.0200, 0.0000],
       [0.9900, 0.0000, 0.0000, ..., 0.0000, 0.0000, 0.0100],
       [1.0000, 0.0000, 0.0000, ..., 0.0000, 0.0000, 0.0000]])

In [3]:
r = np.zeros((1,91))
r[0][0] = -1

r      

array([[-1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000]])

# Part 1: Finding the stationary distribution by recursion

In [9]:
pi = np.zeros((1,91))
pi[0,0] = 1

pi

array([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000]])

In [10]:
pi1 = pi

count = 0
while True:
    pi = pi1@P
    if abs(pi1[0,0]-pi[0,0]) < 0.00000001:
      break
    else:
      pi1 = pi
      count += 1

np.sum(pi), pi, count

(1.0000000000000009,
 array([[0.1461, 0.1315, 0.1170, 0.1030, 0.0896, 0.0771, 0.0655, 0.0550,
         0.0457, 0.0374, 0.0303, 0.0243, 0.0192, 0.0150, 0.0115, 0.0087,
         0.0066, 0.0049, 0.0035, 0.0026, 0.0018, 0.0013, 0.0009, 0.0006,
         0.0004, 0.0003, 0.0002, 0.0001, 0.0001, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000]]),
 45)

In [ ]:
phi = np.sum(pi*r, axis=1)

print("Limiting Phi by recurrsion: ", phi) # long-run average replacement cost

Limiting Phi by recurrsion:  [-0.1461]


# Part 2: Using Poisson equation

In [ ]:
def solve_poisson(r, P): 
  V_coeff = np.identity(91)-P
  V_coeff_and_phi_coeff = np.c_[V_coeff, np.ones((91))]
  V_and_phi = np.linalg.solve(V_coeff_and_phi_coeff[:,1:], r.T) # set V(0) as zero so excluded first row in calculation
  V_1_to_90 = V_and_phi[:-1] # limiting values i.e. V*(1),V*(2)... V*(90)
  V_0_to_90 = np.append(0, V_1_to_90) 
  phi = V_and_phi[-1]

  return V_0_to_90, phi

In [ ]:
V_0_to_90, phi = solve_poisson(r, P)

print("V_0_to_90: ", V_0_to_90)
print("Poisson Limiting Phi: ", phi) # limiting average replacement cost i.e. phi*

V_0_to_90:  [0.0000 0.9488 0.9019 0.8589 0.8193 0.7828 0.7490 0.7177 0.6887 0.6617
 0.6366 0.6131 0.5912 0.5706 0.5513 0.5332 0.5162 0.5001 0.4849 0.4706
 0.4570 0.4441 0.4319 0.4204 0.4094 0.3989 0.3889 0.3794 0.3703 0.3616
 0.3533 0.3454 0.3378 0.3305 0.3235 0.3168 0.3103 0.3041 0.2981 0.2924
 0.2869 0.2815 0.2764 0.2714 0.2666 0.2620 0.2575 0.2531 0.2490 0.2449
 0.2410 0.2371 0.2334 0.2299 0.2264 0.2230 0.2197 0.2165 0.2134 0.2104
 0.2075 0.2046 0.2019 0.1992 0.1965 0.1940 0.1915 0.1890 0.1867 0.1843
 0.1821 0.1799 0.1777 0.1756 0.1735 0.1715 0.1696 0.1676 0.1658 0.1639
 0.1621 0.1604 0.1587 0.1570 0.1553 0.1537 0.1521 0.1506 0.1490 0.1476
 0.1461]
Poisson Limiting Phi:  [-0.1461]


# Part 3: Policy iteration and Value iteration

In [ ]:
P_action0 = P
r_action0 = np.zeros((91))
for i in range(91):
  r_action0[i] = i*0.01 + 0.1

P_action1 = np.zeros((91,91))
r_action1 = np.zeros((91))
for i in range(91):
  P_action1[i][0] = 1
  r_action1[i] = 0.5

## Policy iteration

In [ ]:
best_actions = np.zeros((91)) # initialising with action 0's

for i in range(91): # loop to compare actions at each state (reference state)
  r = np.zeros((91))
  P = np.zeros((91,91))

  for j in range(91): # constructing vector r and matrix P 
    if best_actions[j] ==0: 
      r[j] = r_action0[j]
      P[j] = P_action0[j]
    else: # if action 1 is found to be the best action in previous iterations (for states before the reference state)
      r[j] = r_action1[j]
      P[j] = P_action1[j]
  
  V_0_to_90, _ = solve_poisson(r,P) # V's for the present combination of actions (got after updations to the intialised combination from previous iterations) 

  action0_value = r_action0 + P_action0@V_0_to_90
  action1_value = r_action1 + P_action1@V_0_to_90
  action_values = np.vstack((action0_value,action1_value))
  best_actions = np.argmin(action_values,axis=0)

  if i == 90:
    _, policy_phi = solve_poisson(r,P)

print("best actions:\n", best_actions)
print("preventive actions are taken in states:\n", np.argwhere(best_actions==1).T)
print("Policy iteration Phi: ", policy_phi)

best actions:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
preventive actions are taken in states:
 [[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
  37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60
  61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84
  85 86 87 88 89 90]]
Policy iteration Phi:  0.14491799482409004


## Value iteration

In [ ]:
V = np.zeros((91))

for i in range(91):
  V_action0 = r_action0 + P_action0@V
  V_action1 = r_action1 + P_action1@V
  V_decision = np.minimum(V_action0,V_action1)
  if i == 90:
  	Value_phi = (V_decision - V)
  V = V_decision

print("Final V's:\n", V_decision)
print("Value iteration phi: ", Value_phi[0])

Final V's:
 [13.0229 13.0728 13.1182 13.1596 13.1971 13.2312 13.2620 13.2895 13.3139
 13.3350 13.3526 13.3661 13.3750 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780 13.3780
 13.3780]
Value iteration phi:  0.1449179984802651
